resolver: https://lts.math.bio/bcd-lts-dev.yaml

# package and necessary repos that are not included in the BCD-LTS
packages:
- '.'

# necessary extra-deps that are not included in the BCD-LTS
extra-deps:
  - openid-connect-0.1.0.0

allow-newer: true

flags: {}

ghc-options:
  $locals: -Wall -fdiagnostics-color=always
