resolver: https://lts.math.bio/bcd-lts-dev.yaml

# package and necessary repos that are not included in the BCD-LTS
packages:
- '.'

# necessary extra-deps that are not included in the BCD-LTS
extra-deps:
- git: git://github.com/biocad/openid-connect.git
  commit: 424f8fc70d4d9064f11bbce35f3672982a28ec06

allow-newer: true

flags: {}

ghc-options:
  $locals: -Wall -fdiagnostics-color=always
